-- Create the PLOTS table
CREATE TABLE plots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  location TEXT NOT NULL,
  price DECIMAL NOT NULL,
  size_sqyd INT NOT NULL,
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the PLOT_IMAGES table
CREATE TABLE plot_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  plot_id BIGINT REFERENCES plots(id) ON DELETE CASCADE
);

-- Create the INQUIRIES table
CREATE TABLE inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'NEW', -- NEW, CONTACTED, CLOSED
  plot_id BIGINT REFERENCES plots(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) for all tables
ALTER TABLE plots ENABLE ROW LEVEL SECURITY;
ALTER TABLE plot_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- RLS Policies for PLOTS
CREATE POLICY "Public can read published plots" ON plots FOR SELECT USING (is_published = TRUE);
CREATE POLICY "Admins can do everything on plots" ON plots FOR ALL USING (auth.role() = 'authenticated');

-- RLS Policies for PLOT_IMAGES
CREATE POLICY "Public can read plot images" ON plot_images FOR SELECT USING (TRUE);
CREATE POLICY "Admins can manage plot images" ON plot_images FOR ALL USING (auth.role() = 'authenticated');

-- RLS Policies for INQUIRIES
CREATE POLICY "Anyone can submit an inquiry" ON inquiries FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Admins can manage inquiries" ON inquiries FOR ALL USING (auth.role() = 'authenticated');